import "./globals.css";

import NextArtProvider from "../components/NextArtProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextArtProvider>{children}</NextArtProvider>
      </body>
    </html>
  );
}
